### ISSUE TITLE
expected <string> but got <EOF>

### ISSUE THREAD

**Issue by Haffon** [mohd-akram/jawk#2] opened 2021-02-05 02:00 UTC
This is the json file demo-blank-line.json content:
```
{
    "node_name" : "test_node",

    "log_valid_days" : 7
}
```
This is the jawk command line:
`./jawk '{print _["log_valid_days"]}' demo-blank-line.json`
and this is the command output:
```
demo-blank-line.json: expected <string> but got <EOF> (length 3) at input token 1
<<EOF>>
```
if I remove the blank line of demo-blank-line.json to make it look like this:
```
{
    "node_name" : "test_node",
    "log_valid_days" : 7
}
```
and run the same command line again, then it output:
`7`
My questions is:
1. Why command failed just because of one blank line difference?
2. Why need patch JSON.awk with patch-json-awk.diff?
3. How can I use jawk with blank line json file?

**Comment by Haffon** [comment] 2021-02-05 09:25
I hacked the code, and found below three diff line affected the parse_object function
```
+			key_ = key
+			gsub(/^"|"$/, "", key_)
+			keys=(keys ? keys "\037" : "") key_
```
Is it possible to fix it?

**Comment by mohd-akram** [comment] 2021-02-05 15:58
Thank you for this report! This is fixed in fc4f17cc464f699463f6bcfb45530c21d1c3805d. To answer your questions:

1. This was because of a bug in a modification I made to JSON.awk.
2. To handle line-delimited JSON, and it's also needed for some other features in jawk.
3. It should work now!

**Comment by Haffon** [comment] 2021-02-06 11:35
@mohd-akram Thanks, it work for simple json file now, but I have a little long json file, which cause the jawk command output:
```
some-long.json: expected <string> but got <EOF> (length 3) at input token 5
"type_id" : 1 , <<EOF>>

```

**Comment by mohd-akram** [comment] 2021-02-06 11:49
Hmm, odd. Does this happen with JSON.awk too or just with jawk? Could you provide the file? If not, do you think you'd be able to reduce it to a small sample where the error happens?

**Comment by Haffon** [comment] 2021-02-06 11:56
@mohd-akram It does not happen with JSON.awk 1.4.2. I'm trying to reduce it to a small sample, see you soon.

**Comment by Haffon** [comment] 2021-02-06 12:20
The full file has another special character, which display as ^I when set option with :set list in vim, and it make a little hard for me to  copy and paste the text. even to reduce it to a small sample.

**Comment by mohd-akram** [comment] 2021-02-06 12:25
Hmm, okay. Could you paste the full error message that you get? I might be able to figure it out that way.

EDIT: It seems you did paste the full error but it got parsed in a strange way due to markdown. It's better to wrap errors/code in triple backticks, like so:

```
some-long.json: expected <string> but got <EOF> (length 3) at input token 5
"type_id" : 1 , <<EOF>>
```

Okay, I can reproduce the error now.

**Comment by mohd-akram** [comment] 2021-02-06 13:08
This should be fixed in b5167c42e85ae89783fcf6111c155a180f38f748.

**Comment by Haffon** [comment] 2021-02-06 21:34
Thanks for you fixing.

**Comment by mohd-akram** [comment] 2021-02-07 07:12
Thanks for the reports!

**Closed as completed by mohd-akram** 2021-02-07 07:12 UTC
